name: Pull IPRanges Daily

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression schedules the workflow to run daily at midnight (00:00 UTC)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  pull_ipranges:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Pull Microsoft IP Ranges
      run: |
        git clone --depth 1 --filter=blob:none --sparse https://github.com/lord-alfred/ipranges.git temp-ipranges
        cd temp-ipranges
        git sparse-checkout set microsoft
        cp -r microsoft/* ../
        cd ..
        rm -rf temp-ipranges

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Daily update of Microsoft IP Ranges"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
